name: opinion_distance
channels:
  - defaults
dependencies:
  - asn1crypto=1.3.0
  - blas=1.0
  - boto=2.49.0
  - boto3=1.12.0
  - botocore=1.15.0
  - bz2file=0.98
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.8
  - docutils=0.15.2
  - gensim=3.8.0
  - idna=2.8
  - intel-openmp=2019.4
  - jmespath=0.9.4
  - joblib=0.14.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - llvm-openmp=4.0.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - nltk=3.4.5
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - pip=20.0.2
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - readline=7.0
  - requests=2.22.0
  - s3transfer=0.3.3
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=45.2.0
  - six=1.14.0
  - smart_open=1.9.0
  - sqlite=3.31.1
  - tk=8.6.8
  - urllib3=1.25.8
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - decorator==4.4.1
    - imbalanced-learn==0.6.2
    - imblearn==0.0
    - networkx==2.4
    - pyemd==0.5.1
    - vadersentiment==2.4.1

